PR for completing all the relatedness-ancestry mvp for component for siteQC
lifebit-ai/relate pull request #3
Opened 2020-09-22 16:03 UTC by aldembert

This PR includes all the code cleaning, bug fixing and setup done for including Daniels new code updates from last week for running the full relatedness and ancestry components of the siteQC pipeline done by Vlad.

To test the pipeline in AWS do:

*install all standard dependencies.

git clone https://github.com/lifebit-ai/relate.git

cd relate

git checkout salvador-add-ancestry-mvp

docker build -t lifebitai/relate:2.0dev . -f Dockerfile

*Run aws configure and add the needed s3 configuration

*Run the nextflow pipeline with the required test files:

nextflow main.nf --inputDir 's3://lifebit-featured-datasets/projects/gel/siteqc/ARtestFiles/Annotation_newtest/' --input s3://lifebit-featured-datasets/projects/gel/siteqc/input.csv --inputMichiganLDfile s3://lifebit-featured-datasets/projects/gel/siteqc/MichiganLD_liftover_exclude_regions_PARSED.txt --inputMichiganLDfileExclude s3://lifebit-featured-datasets/projects/gel/siteqc/MichiganLD_liftover_exclude_regions_PARSED.txt --inputAncestryAssignmentProbs s3://lifebit-featured-datasets/projects/gel/siteqc/aggV2_R9_M30K_1KGP3_ancestry_assignment_probs.tsv --inputPCsancestryrelated s3://lifebit-featured-datasets/projects/gel/siteqc/aggV2_bedmerge_30KSNPs_labkeyV9_08062020_update_PCsancestryrelated.tsv --inputFinalPlatekeys s3://lifebit-featured-datasets/projects/gel/siteqc/sampleList.txt --inputProbs200K s3://lifebit-featured-datasets/projects/gel/siteqc/aggV2_ancestry_assignment_probs_1KGP3_200K.tsv --inputUNRELATED_1KGP3 s3://lifebit-featured-datasets/projects/gel/siteqc/UNRELATED_1KGP3.samples --input1KGP3 s3://lifebit-featured-datasets/projects/gel/siteqc/1KGP3.sample_table --inputSuper_pop_codes s3://lifebit-featured-datasets/projects/gel/siteqc/super_pop_codes.tsv --input05both1K100K_eigenvec s3://lifebit-featured-datasets/projects/gel/siteqc/1KGP3_30K_unrel_autosomes.eigenvec --inputGELprojection_proj_eigenvec s3://lifebit-featured-datasets/projects/gel/siteqc/1KGP3_30K_unrel_autosomes.eigenvec_TMPPROJ

This PR uses the docker container "lifebitai/relate:2.0dev"

-------------------------------

Many thanks to contributing to lifebit-ai/relate!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/lifebit-ai/relate/tree/master/.github/CONTRIBUTING.md

2020-09-23 08:24 UTC, cgpu commented on Dockerfile
> +RUN R -e "withr::with_makevars(c(PKG_LIBS = '-liconv'), install.packages('tidyverse',repos='http://cran.us.r-project.org'), assignment = '+=')"
@aldembert out of curiosity, why are we running this with `withr::with_makevars`?

2020-09-23 08:48 UTC, cgpu requested changes
Thanks for the contribs @aldembert!

Do you mind also adding documentation on the new parameters you might have added?

I have tagged you where @Vlad-Dembrovskyi has added docs for `lifebit-ai/siteqc` here:
https://github.com/lifebit-ai/siteqc/pull/12/files#r493310896

The file you need to change is `docs/usage.md`. Have a look at the format
https://github.com/lifebit-ai/siteqc/blob/master/docs/usage.md#required-siteqc-pipeline-arguments

2020-09-23 11:10 UTC, aldembert commented on Dockerfile
> +RUN R -e "withr::with_makevars(c(PKG_LIBS = '-liconv'), install.packages('tidyverse',repos='http://cran.us.r-project.org'), assignment = '+=')"
Very good question. I actually struggled a lot finding that solution. The problem is that without that specific way of running the installation of tidyverse library it wont recognize the required dependencies and environment variables that Tidyverse requires. Without that way of running the package installation this is what you get:

![image](https://user-images.githubusercontent.com/9978265/94004490-674ddd80-fd62-11ea-8445-14597a6092a2.png)
![image](https://user-images.githubusercontent.com/9978265/94004555-7b91da80-fd62-11ea-9a0c-ccbf3ab5be59.png)
![image](https://user-images.githubusercontent.com/9978265/94004610-92d0c800-fd62-11ea-8629-417246d8695f.png)


And after using the "withr" way of installing all gets done correctly for tidyverse:

![image](https://user-images.githubusercontent.com/9978265/94004949-1ee2ef80-fd63-11ea-88c0-0bcb29c8821b.png)
![image](https://user-images.githubusercontent.com/9978265/94005064-4fc32480-fd63-11ea-837f-8554ec000e18.png)

Thats the reason for this @cgpu

2020-09-23 11:43 UTC, cgpu commented on Dockerfile
> +RUN R -e "withr::with_makevars(c(PKG_LIBS = '-liconv'), install.packages('tidyverse',repos='http://cran.us.r-project.org'), assignment = '+=')"
Nice thanks for the explanation @aldembert 👍 !

2020-09-24 09:16 UTC, cgpu approved these changes
Goog to go 👍

2020-09-24 09:48 UTC, merged